name: Cleanup jumphosts

on:
  schedule:
    - cron: 0,15,30,45 * * * *

env:
  RESOURCE_GROUP_NAME: rg-contoso-dev-weu

permissions:
  id-token: write

jobs:
  build:
    name: Cleanup jumphosts
    runs-on: ubuntu-latest
    steps:
      - name: Login with service principal
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Delete jumphosts
        uses: azure/cli@v1
        with:
          inlineScript: |
            vmIds=`az vm list -g ${{ env.RESOURCE_GROUP_NAME }} --query "[?contains(keys(tags), 'product')].id" -o tsv`
            nicIds=`az network nic list -g ${{ env.RESOURCE_GROUP_NAME }} --query "[?contains(keys(tags), 'product')].id" -o tsv`
            if [[ -n "${vmIds}" && -n "${nicIds}" ]]; then
              az vm delete --ids "${vmIds}" -y
              az network nic delete --ids "${nicIds}" -y
            fi