name: Create jumphost

on:
  workflow_dispatch:
    inputs:
      resourceGroupName:
        required: true
        description: Resource group name
      productName:
        required: true
        description: Product name
      ssh:
        required: true
        description: Public SSH key data (base64)

permissions:
  id-token: write

jobs:
  build:
    name: Provision Azure Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login with service principal
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Apply bicep template
        uses: azure/cli@v1
        with:
          inlineScript: |
            az deployment group create \
            -g ${{ github.event.inputs.resourceGroupName }} \
            -f main.bicep \
            -p product=${{ github.event.inputs.productName }} \
            -p sshKeyData=${{ github.event.inputs.ssh }}