name: Delete jumphost

on:
  workflow_dispatch:
    inputs:
      resourceGroupName:
        required: true
        description: Resource group name
      productName:
        required: true
        description: Product name

permissions:
  id-token: write

jobs:
  build:
    name: Delete jumphost
    runs-on: ubuntu-latest
    steps:
      - name: Login with service principal
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Delete jumphost
        uses: azure/cli@v1
        with:
          inlineScript: |
            vmIds=`az vm list --query "[?tags.product=='${{ github.event.inputs.productName }}'].id" -o tsv`
            nicIds=`az network nic list --query "[?tags.product=='${{ github.event.inputs.productName }}'].id" -o tsv`
            if [[ -n "${vmIds}" && -n "${nicIds}" ]]; then
              az vm delete --ids "${vmIds}" -y
              az network nic delete --ids "${nicIds}"
            fi